apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: application
type: Opaque
data:
  USERHOST:    ZGF0YWJhc2VzLXNlcnZpY2UuYXBwbGljYXRpb24uc3ZjLmNsdXN0ZXIubG9jYWw=
  USERUSER:    cm9vdA==
  USERPASS:    eW9uMTMz
  USERDB:      dXNlcnM=
  USERPORT:   MzMwNg==
  GUITARHOST:  ZGF0YWJhc2VzLXNlcnZpY2UuYXBwbGljYXRpb24uc3ZjLmNsdXN0ZXIubG9jYWw=
  GUITARUSER:  cm9vdA==
  GUITARPASS:  eW9uMTMz
  GUITARDB:    cHJvZHVjdF9jYXRhbG9n
  GUITARPORT:  MzMwNg==


