apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
data:
  USERHOST:    ZGF0YWJhc2VzLXNlcnZpY2UuZGVmYXVsdC5zdmMuY2x1c3Rlci5sb2NhbA==
  USERUSER:    cm9vdA==
  USERPASS:    eW9uMTMz
  USERDB:      dXNlcnM=
  USDERPORT:   MzMwNg==
  GUITARHOST:  ZGF0YWJhc2VzLXNlcnZpY2UuZGVmYXVsdC5zdmMuY2x1c3Rlci5sb2NhbA==
  GUITARUSER:  cm9vdA==
  GUITARPASS:  eW9uMTMz
  GUITARDB:    cHJvZHVjdF9jYXRhbG9n
  GUITARPORT:  MzMwNg==












