apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
        - name: flask-app
          image: yonatankaplounov/application:latest
          envFrom:                              # Use 'envFrom' to import all Secret data as environment variables
            - secretRef:
                name: app-secrets
          # resources: 
          #   limits:
          #     cpu: "0.5" 
          #     memory: "1" 
          #   requests:
          #     cpu: "0.5" 
          #     memory: "1"                     
---
apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
spec:
  selector:
    app: flask-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer