apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
  namespace: application
  labels:
    app: flask-app
spec:
  selector:
    app: flask-app
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 80
  type: NodePort
