apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guitars
spec:
  destination:
    name: ''
    namespace: application
    server: 'https://kubernetes.default.svc'
  source:
    path: helm-chart/application
    repoURL: 'https://github.com/YoniKap/projVS'
    targetRevision: HEAD
    helm:
      values: ''
      parameters:
        - name: app.imagePullPolicy
          value: Always
        - name: app.limits.cpu
          value: '0.5'
        - name: appimage.tag
          value: latest
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
