apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guitars
  annotations: 
    argocd-image-updater.argoproj.io/image-list: yonatankaplounov/application
    argocd-image-updater.argoproj.io/git-branch: main
    argocd-image-updater.argoproj.io/image-alias.update-strategy: latest
spec:
  destination:
    name: ''
    namespace: application
    server: 'https://kubernetes.default.svc'
  source:
    path: helm-chart/application
    repoURL: 'https://github.com/YoniKap/projVS'
    targetRevision: HEAD
    helm:
      values: ''
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
