apiVersion: v1
kind: Service
metadata:
  name: databases-service
  namespace: {{.Values.namespace}}
spec:
  selector:
    app: {{.Values.database.name}}
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  type: ClusterIP