name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: test-app
      run: python test.py    
        
    - name: docker-login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: Get Commit SHA
      id: commit_sha
      run: echo "::set-output name=SHA_SHORT::$(git rev-parse --short HEAD)"
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag yonatankaplounov/application:${{ steps.commit_sha.outputs.SHA_SHORT }}
    - name: Push Image Into Repo
      run: docker push yonatankaplounov/application:${{ steps.commit_sha.outputs.SHA_SHORT }}
