name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
   
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Install project dependencies

    - name: Set up Git User Identity
      run: |
        git config --global user.name "${{ github.actor }}"
        git config --global user.email "${{ github.actor }}@users.noreply.github.com"
    

    - name: test-app
      run: python tests.py    
        
    - name: docker-login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: Get Commit SHA
      id: commit_sha
      run: echo "::set-output name=SHA_SHORT::$(git rev-parse --short HEAD)"
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag yonatankaplounov/application:${{ steps.commit_sha.outputs.SHA_SHORT }}
           && docker build . --file Dockerfile --tag yonatankaplounov/application:latest
           
    - name: test compose
      run: docker-compose -f test-compose.yaml up -d
      
    - name: Push Image Into Repo
      run: docker push yonatankaplounov/application:${{ steps.commit_sha.outputs.SHA_SHORT }}
           && docker push yonatankaplounov/application:latest


           
